/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Types {
  export type ValueComparisonStruct = {
    value0: BigNumberish;
    value1: BigNumberish;
    operator: BigNumberish;
  };

  export type ValueComparisonStructOutput = [
    value0: bigint,
    value1: bigint,
    operator: bigint
  ] & { value0: bigint; value1: bigint; operator: bigint };

  export type StopConditionStruct = {
    value: BigNumberish;
    operator: BigNumberish;
  };

  export type StopConditionStructOutput = [value: bigint, operator: bigint] & {
    value: bigint;
    operator: bigint;
  };

  export type TradingStopConditionStruct = {
    stopType: BigNumberish;
    value: BigNumberish;
  };

  export type TradingStopConditionStructOutput = [
    stopType: bigint,
    value: bigint
  ] & { stopType: bigint; value: bigint };

  export type MachineStruct = {
    id: string;
    totalDepositedBaseAmount: BigNumberish;
    totalSwappedBaseAmount: BigNumberish;
    totalReceivedTargetAmount: BigNumberish;
    totalClosedPositionInTargetTokenAmount: BigNumberish;
    totalReceivedFundInBaseTokenAmount: BigNumberish;
    baseTokenBalance: BigNumberish;
    targetTokenBalance: BigNumberish;
    executedBatchAmount: BigNumberish;
    nextScheduledExecutionAt: BigNumberish;
    status: BigNumberish;
    owner: AddressLike;
    ammRouterAddress: AddressLike;
    baseTokenAddress: AddressLike;
    targetTokenAddress: AddressLike;
    startAt: BigNumberish;
    batchVolume: BigNumberish;
    frequency: BigNumberish;
    openingPositionCondition: Types.ValueComparisonStruct;
    stopConditions: Types.StopConditionStruct[];
    takeProfitCondition: Types.TradingStopConditionStruct;
    stopLossCondition: Types.TradingStopConditionStruct;
    ammRouterVersion: BigNumberish;
  };

  export type MachineStructOutput = [
    id: string,
    totalDepositedBaseAmount: bigint,
    totalSwappedBaseAmount: bigint,
    totalReceivedTargetAmount: bigint,
    totalClosedPositionInTargetTokenAmount: bigint,
    totalReceivedFundInBaseTokenAmount: bigint,
    baseTokenBalance: bigint,
    targetTokenBalance: bigint,
    executedBatchAmount: bigint,
    nextScheduledExecutionAt: bigint,
    status: bigint,
    owner: string,
    ammRouterAddress: string,
    baseTokenAddress: string,
    targetTokenAddress: string,
    startAt: bigint,
    batchVolume: bigint,
    frequency: bigint,
    openingPositionCondition: Types.ValueComparisonStructOutput,
    stopConditions: Types.StopConditionStructOutput[],
    takeProfitCondition: Types.TradingStopConditionStructOutput,
    stopLossCondition: Types.TradingStopConditionStructOutput,
    ammRouterVersion: bigint
  ] & {
    id: string;
    totalDepositedBaseAmount: bigint;
    totalSwappedBaseAmount: bigint;
    totalReceivedTargetAmount: bigint;
    totalClosedPositionInTargetTokenAmount: bigint;
    totalReceivedFundInBaseTokenAmount: bigint;
    baseTokenBalance: bigint;
    targetTokenBalance: bigint;
    executedBatchAmount: bigint;
    nextScheduledExecutionAt: bigint;
    status: bigint;
    owner: string;
    ammRouterAddress: string;
    baseTokenAddress: string;
    targetTokenAddress: string;
    startAt: bigint;
    batchVolume: bigint;
    frequency: bigint;
    openingPositionCondition: Types.ValueComparisonStructOutput;
    stopConditions: Types.StopConditionStructOutput[];
    takeProfitCondition: Types.TradingStopConditionStructOutput;
    stopLossCondition: Types.TradingStopConditionStructOutput;
    ammRouterVersion: bigint;
  };
}

export declare namespace Params {
  export type CreateMachineParamsStruct = {
    id: string;
    owner: AddressLike;
    ammRouterAddress: AddressLike;
    baseTokenAddress: AddressLike;
    targetTokenAddress: AddressLike;
    ammRouterVersion: BigNumberish;
    startAt: BigNumberish;
    batchVolume: BigNumberish;
    stopConditions: Types.StopConditionStruct[];
    frequency: BigNumberish;
    openingPositionCondition: Types.ValueComparisonStruct;
    takeProfitCondition: Types.TradingStopConditionStruct;
    stopLossCondition: Types.TradingStopConditionStruct;
  };

  export type CreateMachineParamsStructOutput = [
    id: string,
    owner: string,
    ammRouterAddress: string,
    baseTokenAddress: string,
    targetTokenAddress: string,
    ammRouterVersion: bigint,
    startAt: bigint,
    batchVolume: bigint,
    stopConditions: Types.StopConditionStructOutput[],
    frequency: bigint,
    openingPositionCondition: Types.ValueComparisonStructOutput,
    takeProfitCondition: Types.TradingStopConditionStructOutput,
    stopLossCondition: Types.TradingStopConditionStructOutput
  ] & {
    id: string;
    owner: string;
    ammRouterAddress: string;
    baseTokenAddress: string;
    targetTokenAddress: string;
    ammRouterVersion: bigint;
    startAt: bigint;
    batchVolume: bigint;
    stopConditions: Types.StopConditionStructOutput[];
    frequency: bigint;
    openingPositionCondition: Types.ValueComparisonStructOutput;
    takeProfitCondition: Types.TradingStopConditionStructOutput;
    stopLossCondition: Types.TradingStopConditionStructOutput;
  };

  export type UpdateMachineParamsStruct = {
    id: string;
    startAt: BigNumberish;
    batchVolume: BigNumberish;
    stopConditions: Types.StopConditionStruct[];
    frequency: BigNumberish;
    openingPositionCondition: Types.ValueComparisonStruct;
    takeProfitCondition: Types.TradingStopConditionStruct;
    stopLossCondition: Types.TradingStopConditionStruct;
  };

  export type UpdateMachineParamsStructOutput = [
    id: string,
    startAt: bigint,
    batchVolume: bigint,
    stopConditions: Types.StopConditionStructOutput[],
    frequency: bigint,
    openingPositionCondition: Types.ValueComparisonStructOutput,
    takeProfitCondition: Types.TradingStopConditionStructOutput,
    stopLossCondition: Types.TradingStopConditionStructOutput
  ] & {
    id: string;
    startAt: bigint;
    batchVolume: bigint;
    stopConditions: Types.StopConditionStructOutput[];
    frequency: bigint;
    openingPositionCondition: Types.ValueComparisonStructOutput;
    takeProfitCondition: Types.TradingStopConditionStructOutput;
    stopLossCondition: Types.TradingStopConditionStructOutput;
  };

  export type UpdateMachineClosingPositionStatsParamsStruct = {
    id: string;
    actor: AddressLike;
    swappedTargetTokenAmount: BigNumberish;
    receivedBaseTokenAmount: BigNumberish;
  };

  export type UpdateMachineClosingPositionStatsParamsStructOutput = [
    id: string,
    actor: string,
    swappedTargetTokenAmount: bigint,
    receivedBaseTokenAmount: bigint
  ] & {
    id: string;
    actor: string;
    swappedTargetTokenAmount: bigint;
    receivedBaseTokenAmount: bigint;
  };

  export type UpdateMachineDepositParamsStruct = {
    actor: AddressLike;
    id: string;
    amount: BigNumberish;
    tokenAddress: AddressLike;
  };

  export type UpdateMachineDepositParamsStructOutput = [
    actor: string,
    id: string,
    amount: bigint,
    tokenAddress: string
  ] & { actor: string; id: string; amount: bigint; tokenAddress: string };

  export type UpdateMachineStatusParamsStruct = {
    actor: AddressLike;
    id: string;
    status: BigNumberish;
  };

  export type UpdateMachineStatusParamsStructOutput = [
    actor: string,
    id: string,
    status: bigint
  ] & { actor: string; id: string; status: bigint };

  export type UpdateMachineTradingStatsParamsStruct = {
    actor: AddressLike;
    id: string;
    swappedBaseTokenAmount: BigNumberish;
    receivedTargetTokenAmount: BigNumberish;
  };

  export type UpdateMachineTradingStatsParamsStructOutput = [
    actor: string,
    id: string,
    swappedBaseTokenAmount: bigint,
    receivedTargetTokenAmount: bigint
  ] & {
    actor: string;
    id: string;
    swappedBaseTokenAmount: bigint;
    receivedTargetTokenAmount: bigint;
  };

  export type UpdateMachineWithdrawalParamsStruct = {
    actor: AddressLike;
    id: string;
  };

  export type UpdateMachineWithdrawalParamsStructOutput = [
    actor: string,
    id: string
  ] & { actor: string; id: string };
}

export interface MachineRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR"
      | "PERCENTAGE_PRECISION"
      | "RELAYER"
      | "allowedInteractiveAddresses"
      | "blacklistedIdMap"
      | "getBalanceInfoOf"
      | "getOwnerOf"
      | "getRoleAdmin"
      | "getStopConditionsOf"
      | "getTradingInfoOf"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "initializeUserMachine"
      | "isAbleToClose"
      | "isAbleToDeposit"
      | "isAbleToPause"
      | "isAbleToRestart"
      | "isAbleToUpdate"
      | "isAbleToWithdraw"
      | "isOwnerOf"
      | "isReadyToClosePosition"
      | "isReadyToSwap"
      | "machines"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "renounceRole"
      | "revokeRole"
      | "shouldCloseMachine"
      | "shouldOpenPosition"
      | "shouldStopLoss"
      | "shouldTakeProfit"
      | "supportsInterface"
      | "transferOwnership"
      | "unpause"
      | "updateMachine"
      | "updateMachineClosingPositionStats"
      | "updateMachineDepositStats"
      | "updateMachineStatus"
      | "updateMachineTradingStats"
      | "updateMachineWithdrawalStats"
      | "whitelistAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressWhitelisted"
      | "Initialized"
      | "OwnershipTransferred"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
      | "machineInitialized"
      | "machineUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "OPERATOR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PERCENTAGE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "RELAYER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allowedInteractiveAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistedIdMap",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalanceInfoOf",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getOwnerOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStopConditionsOf",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTradingInfoOf",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeUserMachine",
    values: [Params.CreateMachineParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isAbleToClose",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAbleToDeposit",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAbleToPause",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAbleToRestart",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAbleToUpdate",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAbleToWithdraw",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOwnerOf",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isReadyToClosePosition",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isReadyToSwap",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "machines", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shouldCloseMachine",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "shouldOpenPosition",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shouldStopLoss",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shouldTakeProfit",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateMachine",
    values: [Params.UpdateMachineParamsStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMachineClosingPositionStats",
    values: [Params.UpdateMachineClosingPositionStatsParamsStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMachineDepositStats",
    values: [Params.UpdateMachineDepositParamsStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMachineStatus",
    values: [Params.UpdateMachineStatusParamsStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMachineTradingStats",
    values: [Params.UpdateMachineTradingStatsParamsStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMachineWithdrawalStats",
    values: [Params.UpdateMachineWithdrawalParamsStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistAddress",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "OPERATOR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PERCENTAGE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "RELAYER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowedInteractiveAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistedIdMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalanceInfoOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwnerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStopConditionsOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradingInfoOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeUserMachine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAbleToClose",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAbleToDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAbleToPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAbleToRestart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAbleToUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAbleToWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwnerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isReadyToClosePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isReadyToSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "machines", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "shouldCloseMachine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shouldOpenPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shouldStopLoss",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shouldTakeProfit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateMachine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMachineClosingPositionStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMachineDepositStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMachineStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMachineTradingStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMachineWithdrawalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistAddress",
    data: BytesLike
  ): Result;
}

export namespace AddressWhitelistedEvent {
  export type InputTuple = [
    actor: AddressLike,
    mintAddress: AddressLike,
    value: boolean
  ];
  export type OutputTuple = [
    actor: string,
    mintAddress: string,
    value: boolean
  ];
  export interface OutputObject {
    actor: string;
    mintAddress: string;
    value: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace machineInitializedEvent {
  export type InputTuple = [
    actor: AddressLike,
    machineId: string,
    owner: AddressLike,
    machineData: Types.MachineStruct,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    actor: string,
    machineId: string,
    owner: string,
    machineData: Types.MachineStructOutput,
    timestamp: bigint
  ];
  export interface OutputObject {
    actor: string;
    machineId: string;
    owner: string;
    machineData: Types.MachineStructOutput;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace machineUpdatedEvent {
  export type InputTuple = [
    actor: AddressLike,
    machineId: string,
    owner: AddressLike,
    reason: string,
    machineData: Types.MachineStruct,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    actor: string,
    machineId: string,
    owner: string,
    reason: string,
    machineData: Types.MachineStructOutput,
    timestamp: bigint
  ];
  export interface OutputObject {
    actor: string;
    machineId: string;
    owner: string;
    reason: string;
    machineData: Types.MachineStructOutput;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MachineRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MachineRegistry;
  waitForDeployment(): Promise<this>;

  interface: MachineRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR: TypedContractMethod<[], [string], "view">;

  PERCENTAGE_PRECISION: TypedContractMethod<[], [bigint], "view">;

  RELAYER: TypedContractMethod<[], [string], "view">;

  allowedInteractiveAddresses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  blacklistedIdMap: TypedContractMethod<[arg0: string], [boolean], "view">;

  getBalanceInfoOf: TypedContractMethod<
    [machineId: string],
    [[bigint, bigint]],
    "view"
  >;

  getOwnerOf: TypedContractMethod<[machineId: string], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getStopConditionsOf: TypedContractMethod<
    [machineId: string],
    [Types.StopConditionStructOutput[]],
    "view"
  >;

  getTradingInfoOf: TypedContractMethod<
    [machineId: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        Types.ValueComparisonStructOutput,
        Types.TradingStopConditionStructOutput,
        Types.TradingStopConditionStructOutput
      ]
    ],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  initializeUserMachine: TypedContractMethod<
    [params: Params.CreateMachineParamsStruct],
    [void],
    "nonpayable"
  >;

  isAbleToClose: TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;

  isAbleToDeposit: TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;

  isAbleToPause: TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;

  isAbleToRestart: TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;

  isAbleToUpdate: TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;

  isAbleToWithdraw: TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;

  isOwnerOf: TypedContractMethod<
    [machineId: string, target: AddressLike],
    [boolean],
    "view"
  >;

  isReadyToClosePosition: TypedContractMethod<
    [machineId: string],
    [boolean],
    "view"
  >;

  isReadyToSwap: TypedContractMethod<[machineId: string], [boolean], "view">;

  machines: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        Types.ValueComparisonStructOutput,
        Types.TradingStopConditionStructOutput,
        Types.TradingStopConditionStructOutput,
        bigint
      ] & {
        id: string;
        totalDepositedBaseAmount: bigint;
        totalSwappedBaseAmount: bigint;
        totalReceivedTargetAmount: bigint;
        totalClosedPositionInTargetTokenAmount: bigint;
        totalReceivedFundInBaseTokenAmount: bigint;
        baseTokenBalance: bigint;
        targetTokenBalance: bigint;
        executedBatchAmount: bigint;
        nextScheduledExecutionAt: bigint;
        status: bigint;
        owner: string;
        ammRouterAddress: string;
        baseTokenAddress: string;
        targetTokenAddress: string;
        startAt: bigint;
        batchVolume: bigint;
        frequency: bigint;
        openingPositionCondition: Types.ValueComparisonStructOutput;
        takeProfitCondition: Types.TradingStopConditionStructOutput;
        stopLossCondition: Types.TradingStopConditionStructOutput;
        ammRouterVersion: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  shouldCloseMachine: TypedContractMethod<
    [machineId: string],
    [boolean],
    "view"
  >;

  shouldOpenPosition: TypedContractMethod<
    [
      machineId: string,
      swappedBaseTokenAmount: BigNumberish,
      receivedTargetTokenAmount: BigNumberish
    ],
    [boolean],
    "view"
  >;

  shouldStopLoss: TypedContractMethod<
    [
      machineId: string,
      swappedTargetTokenAmount: BigNumberish,
      receivedBaseTokenAmount: BigNumberish
    ],
    [boolean],
    "view"
  >;

  shouldTakeProfit: TypedContractMethod<
    [
      machineId: string,
      swappedTargetTokenAmount: BigNumberish,
      receivedBaseTokenAmount: BigNumberish
    ],
    [boolean],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateMachine: TypedContractMethod<
    [params: Params.UpdateMachineParamsStruct, reason: string],
    [void],
    "nonpayable"
  >;

  updateMachineClosingPositionStats: TypedContractMethod<
    [
      params: Params.UpdateMachineClosingPositionStatsParamsStruct,
      reason: string
    ],
    [void],
    "nonpayable"
  >;

  updateMachineDepositStats: TypedContractMethod<
    [params: Params.UpdateMachineDepositParamsStruct, reason: string],
    [void],
    "nonpayable"
  >;

  updateMachineStatus: TypedContractMethod<
    [params: Params.UpdateMachineStatusParamsStruct, reason: string],
    [void],
    "nonpayable"
  >;

  updateMachineTradingStats: TypedContractMethod<
    [params: Params.UpdateMachineTradingStatsParamsStruct, reason: string],
    [void],
    "nonpayable"
  >;

  updateMachineWithdrawalStats: TypedContractMethod<
    [params: Params.UpdateMachineWithdrawalParamsStruct, reason: string],
    [void],
    "nonpayable"
  >;

  whitelistAddress: TypedContractMethod<
    [interactiveAddress: AddressLike, value: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PERCENTAGE_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RELAYER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowedInteractiveAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "blacklistedIdMap"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBalanceInfoOf"
  ): TypedContractMethod<[machineId: string], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "getOwnerOf"
  ): TypedContractMethod<[machineId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getStopConditionsOf"
  ): TypedContractMethod<
    [machineId: string],
    [Types.StopConditionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTradingInfoOf"
  ): TypedContractMethod<
    [machineId: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        Types.ValueComparisonStructOutput,
        Types.TradingStopConditionStructOutput,
        Types.TradingStopConditionStructOutput
      ]
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeUserMachine"
  ): TypedContractMethod<
    [params: Params.CreateMachineParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAbleToClose"
  ): TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAbleToDeposit"
  ): TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAbleToPause"
  ): TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAbleToRestart"
  ): TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAbleToUpdate"
  ): TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAbleToWithdraw"
  ): TypedContractMethod<
    [machineId: string, owner: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOwnerOf"
  ): TypedContractMethod<
    [machineId: string, target: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isReadyToClosePosition"
  ): TypedContractMethod<[machineId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isReadyToSwap"
  ): TypedContractMethod<[machineId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "machines"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        Types.ValueComparisonStructOutput,
        Types.TradingStopConditionStructOutput,
        Types.TradingStopConditionStructOutput,
        bigint
      ] & {
        id: string;
        totalDepositedBaseAmount: bigint;
        totalSwappedBaseAmount: bigint;
        totalReceivedTargetAmount: bigint;
        totalClosedPositionInTargetTokenAmount: bigint;
        totalReceivedFundInBaseTokenAmount: bigint;
        baseTokenBalance: bigint;
        targetTokenBalance: bigint;
        executedBatchAmount: bigint;
        nextScheduledExecutionAt: bigint;
        status: bigint;
        owner: string;
        ammRouterAddress: string;
        baseTokenAddress: string;
        targetTokenAddress: string;
        startAt: bigint;
        batchVolume: bigint;
        frequency: bigint;
        openingPositionCondition: Types.ValueComparisonStructOutput;
        takeProfitCondition: Types.TradingStopConditionStructOutput;
        stopLossCondition: Types.TradingStopConditionStructOutput;
        ammRouterVersion: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shouldCloseMachine"
  ): TypedContractMethod<[machineId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "shouldOpenPosition"
  ): TypedContractMethod<
    [
      machineId: string,
      swappedBaseTokenAmount: BigNumberish,
      receivedTargetTokenAmount: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "shouldStopLoss"
  ): TypedContractMethod<
    [
      machineId: string,
      swappedTargetTokenAmount: BigNumberish,
      receivedBaseTokenAmount: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "shouldTakeProfit"
  ): TypedContractMethod<
    [
      machineId: string,
      swappedTargetTokenAmount: BigNumberish,
      receivedBaseTokenAmount: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMachine"
  ): TypedContractMethod<
    [params: Params.UpdateMachineParamsStruct, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMachineClosingPositionStats"
  ): TypedContractMethod<
    [
      params: Params.UpdateMachineClosingPositionStatsParamsStruct,
      reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMachineDepositStats"
  ): TypedContractMethod<
    [params: Params.UpdateMachineDepositParamsStruct, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMachineStatus"
  ): TypedContractMethod<
    [params: Params.UpdateMachineStatusParamsStruct, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMachineTradingStats"
  ): TypedContractMethod<
    [params: Params.UpdateMachineTradingStatsParamsStruct, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMachineWithdrawalStats"
  ): TypedContractMethod<
    [params: Params.UpdateMachineWithdrawalParamsStruct, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whitelistAddress"
  ): TypedContractMethod<
    [interactiveAddress: AddressLike, value: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AddressWhitelisted"
  ): TypedContractEvent<
    AddressWhitelistedEvent.InputTuple,
    AddressWhitelistedEvent.OutputTuple,
    AddressWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "machineInitialized"
  ): TypedContractEvent<
    machineInitializedEvent.InputTuple,
    machineInitializedEvent.OutputTuple,
    machineInitializedEvent.OutputObject
  >;
  getEvent(
    key: "machineUpdated"
  ): TypedContractEvent<
    machineUpdatedEvent.InputTuple,
    machineUpdatedEvent.OutputTuple,
    machineUpdatedEvent.OutputObject
  >;

  filters: {
    "AddressWhitelisted(address,address,bool)": TypedContractEvent<
      AddressWhitelistedEvent.InputTuple,
      AddressWhitelistedEvent.OutputTuple,
      AddressWhitelistedEvent.OutputObject
    >;
    AddressWhitelisted: TypedContractEvent<
      AddressWhitelistedEvent.InputTuple,
      AddressWhitelistedEvent.OutputTuple,
      AddressWhitelistedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "machineInitialized(address,string,address,tuple,uint256)": TypedContractEvent<
      machineInitializedEvent.InputTuple,
      machineInitializedEvent.OutputTuple,
      machineInitializedEvent.OutputObject
    >;
    machineInitialized: TypedContractEvent<
      machineInitializedEvent.InputTuple,
      machineInitializedEvent.OutputTuple,
      machineInitializedEvent.OutputObject
    >;

    "machineUpdated(address,string,address,string,tuple,uint256)": TypedContractEvent<
      machineUpdatedEvent.InputTuple,
      machineUpdatedEvent.OutputTuple,
      machineUpdatedEvent.OutputObject
    >;
    machineUpdated: TypedContractEvent<
      machineUpdatedEvent.InputTuple,
      machineUpdatedEvent.OutputTuple,
      machineUpdatedEvent.OutputObject
    >;
  };
}
